<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>48bef67584deadde5fb3f63c</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-11-17 15:32:35</createtime><buildsignature>Local.Unknown.Unknown.1.66.139.1020-1.200.000.464.Release</buildsignature><categoryid>waitstaff_situation.py:70</categoryid><desyncid>48bef67584deadde5fb3f63c</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'NoneType' object has no attribute '_try_change_order_status')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 209, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v161b\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v161b\zone_tick.py", line 81, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 475, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 112, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 217, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 3811, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 770, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 2912, in transition&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 1320, in end_transition&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\transition_sequence.py", line 450, in _clear_target_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6908, in on_removed_from_queue&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\social\social_super_interaction.py", line 1551, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5005, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6986, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6030, in _trigger_interaction_exited_pipeline_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 266, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 375, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\restaurants\waitstaff_situation.py", line 65, in handle_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\restaurants\waitstaff_situation.py", line 70, in _on_interaction_of_interest_complete&#13;&#10;AttributeError: 'NoneType' object has no attribute '_try_change_order_status'rtim=0&#13;&#10;Client Session Time: 87.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;Origin Version: 10,5,8,17910&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.18363 GPU: AMD Radeon R7 200 Series aticfx64.dll 26.20.12028.2, GUID: D7B71EE2-2B7D-11CF-F974-E8ECBBC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>48bef67584deadde5fb3f63c</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-11-17 15:43:02</createtime><buildsignature>Local.Unknown.Unknown.1.66.139.1020-1.200.000.464.Release</buildsignature><categoryid>object_manager.py:673</categoryid><desyncid>48bef67584deadde5fb3f63c</desyncid><systemconfig/><screenshot/><desyncdata>Exception applying attributes to object object_Photo_PortraitMedium:0x08360c346ce80de9 (KeyError: object_Photo_PortraitMedium(0x08360c346ce80de9))&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\script_object.py", line 2101, in attributes&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\game_object.py", line 1337, in load_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\script_object.py", line 2111, in load_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\script_object.py", line 2200, in load&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\object_marketplace_component.py", line 567, in load&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\object_marketplace_component.py", line 368, in _set_expired&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\object_marketplace_component.py", line 107, in leave_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\game_object.py", line 397, in remove_dynamic_tags&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 673, in remove_tags_on_object_from_cache&#13;&#10;KeyError: object_Photo_PortraitMedium(0x08360c346ce80de9)rtim=0&#13;&#10;Client Session Time: 87.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;Origin Version: 10,5,8,17910&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.18363 GPU: AMD Radeon R7 200 Series aticfx64.dll 26.20.12028.2, GUID: D7B71EE2-2B7D-11CF-F974-E8ECBBC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>48bef67584deadde5fb3f63c</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-11-17 15:51:25</createtime><buildsignature>Local.Unknown.Unknown.1.66.139.1020-1.200.000.464.Release</buildsignature><categoryid>test_variants.py:1489</categoryid><desyncid>48bef67584deadde5fb3f63c</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.terrian_MarchAround'&gt; (AttributeError: 'NoneType' object has no attribute 'aspects')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 395, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\interaction_commands.py", line 210, in has_choices&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\choices.py", line 170, in is_valid_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2570, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 598, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 130, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_events.py", line 185, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 1489, in __call__&#13;&#10;AttributeError: 'NoneType' object has no attribute 'aspects'rtim=0&#13;&#10;Client Session Time: 87.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;Origin Version: 10,5,8,17910&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.18363 GPU: AMD Radeon R7 200 Series aticfx64.dll 26.20.12028.2, GUID: D7B71EE2-2B7D-11CF-F974-E8ECBBC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>48bef67584deadde5fb3f63c</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-11-17 19:09:15</createtime><buildsignature>Local.Unknown.Unknown.1.66.139.1020-1.200.000.464.Release</buildsignature><categoryid>exit_condition_manager.py:61</categoryid><desyncid>48bef67584deadde5fb3f63c</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (AttributeError: 'NoneType' object has no attribute 'in_minutes')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 212, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 335, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6061, in &lt;lambda&gt;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 5796, in attach_conditional_actions&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\exit_condition_manager.py", line 194, in attach_conditions&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\exit_condition_manager.py", line 61, in attach&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\statistic_conditions.py", line 841, in attach_to_ownerAttributeError: 'NoneType' object has no attribute 'in_minutes'rtim=0&#13;&#10;Client Session Time: 87.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;Origin Version: 10,5,8,17910&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.18363 GPU: AMD Radeon R7 200 Series aticfx64.dll 26.20.12028.2, GUID: D7B71EE2-2B7D-11CF-F974-E8ECBBC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>48bef67584deadde5fb3f63c</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-11-17 19:09:58</createtime><buildsignature>Local.Unknown.Unknown.1.66.139.1020-1.200.000.464.Release</buildsignature><categoryid>exit_condition_manager.py:61</categoryid><desyncid>48bef67584deadde5fb3f63c</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (AttributeError: 'NoneType' object has no attribute 'in_minutes')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 212, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 335, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6061, in &lt;lambda&gt;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 5796, in attach_conditional_actions&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\exit_condition_manager.py", line 194, in attach_conditions&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\exit_condition_manager.py", line 61, in attach&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\statistic_conditions.py", line 841, in attach_to_ownerAttributeError: 'NoneType' object has no attribute 'in_minutes'rtim=0&#13;&#10;Client Session Time: 87.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;Origin Version: 10,5,8,17910&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.18363 GPU: AMD Radeon R7 200 Series aticfx64.dll 26.20.12028.2, GUID: D7B71EE2-2B7D-11CF-F974-E8ECBBC2D735&#13; &#10;</desyncdata></report>
</root>